"""empty message

Revision ID: 28077ad3754a
Revises: 
Create Date: 2024-05-11 15:46:08.602339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28077ad3754a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('aec_start_date', sa.Date(), nullable=True),
    sa.Column('pri_product_role', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('ci_age', sa.Integer(), nullable=True),
    sa.Column('ci_gender', sa.String(), nullable=True),
    sa.Column('aec_outcome', sa.Integer(), nullable=True),
    sa.Column('results', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
