"""empty message

Revision ID: bcc9987d987c
Revises: 28077ad3754a
Create Date: 2024-05-12 10:16:59.116506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc9987d987c'
down_revision = '28077ad3754a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cereals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mfr', sa.String(length=1), nullable=False),
    sa.Column('isCold', sa.Boolean(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein', sa.Integer(), nullable=True),
    sa.Column('fat', sa.Integer(), nullable=True),
    sa.Column('sodium', sa.Integer(), nullable=True),
    sa.Column('fiber', sa.Integer(), nullable=True),
    sa.Column('carbo', sa.Integer(), nullable=True),
    sa.Column('sugars', sa.Integer(), nullable=True),
    sa.Column('potass', sa.Integer(), nullable=True),
    sa.Column('vitamins', sa.Integer(), nullable=True),
    sa.Column('shelf', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cup', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.INTEGER(), nullable=False),
    sa.Column('created_date', sa.DATE(), nullable=True),
    sa.Column('aec_start_date', sa.DATE(), nullable=True),
    sa.Column('pri_product_role', sa.VARCHAR(), nullable=True),
    sa.Column('brand_name', sa.VARCHAR(), nullable=True),
    sa.Column('ci_age', sa.INTEGER(), nullable=True),
    sa.Column('ci_gender', sa.VARCHAR(), nullable=True),
    sa.Column('aec_outcome', sa.INTEGER(), nullable=True),
    sa.Column('results', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.drop_table('cereals')
    # ### end Alembic commands ###
